### ISSUE TITLE
Write tests for current endpoints

### ISSUE THREAD

**Issue by edmundlam** [prateeksan/chesspi#38]
- [x] `/games`
- [x] `/games/1`
- [x] `/games/1?format=pgn`
- [x] `/games?format=`
- [x] `/games?name=`
- [x] `/games?eco=`
- [x] `/games?name=&format=&eco=`

- [x] `/players`
- [x] `/players/1`
- [x] `/players?name=chandler`

- [x] `/eco_codes`

**Comment by prateeksan** [comment]
Loving the checkboxes!
